### ISSUE TITLE
[Feature Request] Optionally utilize CFullLoader instead of FullLoader for performance gains

### ISSUE THREAD

**Issue by henrywintif** [outcatcher/pyyaml-typed#13]
I suggest we replace `FullLoader` with `CFullLoader` at [`loader.py:4`](https://github.com/outcatcher/pyyaml-typed/blob/113bac246307e1ba8bc554c91595ab223564122e/tyaml/loader.py#L4).

In my particular case, my script went from running in 17.27 minutes (1035981ms) to 2.49 minutes (149616ms) by only making the change suggested above. This is an 85.6% reduction in runtime in this particular case.

I would like to default to using the `CFullLoader` and use `FullLoader` when `CFullLoader` is unavailable.

@outcatcher I will make a PR for this. I would like your input on a couple things:
* Is this is a feature that you like and would be okay merging?
* Are you familiar with LibYAML/`yaml.CLoader`? If so, are you aware of any peculiarities/gotchas I should look out for?

**Comment by outcatcher** [comment]
It would be a nice feature to have. I haven't used it before. 

As far as I can see, it requires compilation from sources, so I suppose it should fallback to FullLoader anyway.

I don't think there should be problems besides that.

**Comment by henrywintif** [comment]
@outcatcher thanks, I'm making a PR now. I'm taking cues from the [pylibyaml](https://github.com/philsphicas/pylibyaml) package

**Comment by henrywintif** [comment]
@outcatcher are you making a new release for this merge?

**Comment by outcatcher** [comment]
Yes, I will make it later today :)

**Comment by henrywintif** [comment]
Released in [v0.1.3](https://github.com/outcatcher/pyyaml-typed/releases/tag/v0.1.3)
